name: "Docker Builder/Pusher"
run-name: ${{ github.actor }} is building/pushing docker images.

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      cli-image:
        required: true
        type: string
    secrets:
      gcr-service-key:
        required: true
      github-access-token:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.gcr-service-key }}
      -
        name: Pull generator image
        run: docker pull ${{ inputs.cli-image }}
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.github-access-token }}
      -
        name: Build, and Push
        run: docker run --rm -v "$(pwd):/repos/${{ inputs.project-name }}" ${{ inputs.cli-image }} build -pdev -ls ${{ inputs.project-name }}
