name: "Release Notes Generator"
run-name: ${{ github.actor }} is generating release notes.
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      generator-image:
        required: true
        type: string
      flags:
        required: false
        type: string
    secrets:
      gcr-service-key:
        required: true
      github-access-token:
        required: true
jobs:
  generate-release-notes:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.gcr-service-key }}
      -
        name: Pull generator image
        run: docker pull ${{ inputs.generator-image }}
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.github-access-token }}
      -
        name: Publish release notes
        run: docker run --rm -v "$(pwd):/repos/${{ inputs.project-name }}" --env GOOGLE_API_SERVICE_CREDENTIALS='${{ secrets.gcr-service-key }}' ${{ inputs.generator-image }} changelog publish ${{ inputs.project-name }} ${{ inputs.flags }}