name: "Vault Secrets"
on:
  workflow_call:
    inputs:
      vault-url:
        required: true
        type: string
      role:
        required: true
        type: string
      vault-secrets:
        required: true
        type: string
      run-on:
        required: true
        type: string
      jwt-aud:
        required: false
        type: string
jobs:
  retrieve-secret:
        permissions:
            contents: read
            id-token: write
        runs-on: ${{ inputs.run-on }}
        steps:
          - name: Import Secrets
            id: secrets
            uses: hashicorp/vault-action@v2
            with:
              url: ${{ inputs.vault-url }}
              caCertificate: ${{ secrets.VAULT_CA_CERT }}
              role: ${{ inputs.role }}
              method: jwt
              jwtGithubAudience: ${{ inputs.jwt-aud }}
              secrets: ${{ inputs.secrets }}