name: "Vault Secrets"
on:
  workflow_call:
    inputs:
      vault-url:
        required: true
        type: string
      vault-secrets:
        required: true
        type: string
      is_gcp_token:
        required: false
        default: false
        type: boolean
jobs:
  retrieve-secret:
        permissions:
            contents: read
            id-token: write
        runs-on: [self-hosted, prod]
        steps:
          - name: Import Secrets
            id: secrets
            uses: hashicorp/vault-action@v2
            with:
              url: ${{ inputs.vault-url }}
              caCertificate: ${{ secrets.VAULT_CA_CERT }}
              role: github-actions
              method: jwt
              path: github-actions
              tlsSkipVerify: true
              secrets: ${{ inputs.secrets }}
          - 
            name: Nomalize oauth token
            id: token
            if: ${{ inputs.is_gcp_token }}
            run: |
              echo "GCP_TOKEN=$(echo ${{ steps.secrets.outputs.DOCKER_TOKEN }} | cut -f1,2,3 -d'.')" >> $GITHUB_OUTPUT
        outputs:
          output1: ${{ steps.token.outputs.GCP_TOKEN }}
