name: "Vault Secrets"
on:
  workflow_call:
    inputs:
      vault-url:
        required: true
        type: string
      vault-secrets:
        required: true
        type: string
jobs:
  retrieve-secret:
        permissions:
            contents: read
            id-token: write
        runs-on: [self-hosted, prod]
        steps:
          - name: Import Secrets
            id: secrets
            uses: hashicorp/vault-action@v2
            with:
              url: ${{ inputs.vault-url }}
              caCertificate: ${{ secrets.VAULT_CA_CERT }}
              role: github-actions
              method: jwt
              path: github-actions
              tlsSkipVerify: true
              secrets: ${{ inputs.secrets }}
